
import mongoose from 'mongoose';

beforeAll(async () => {
  console.log('Setting up tests...');
});

beforeEach(async () => {
  console.log('Cleaning up before each test...');
});

afterAll(async () => {
  console.log('Cleaning up after all tests...');
});

export const mockAIService = {
  generateSummary: jest.fn().mockResolvedValue('Test summary generated by A.I.')
}